app_name = "abc_billing"
app_title = "Billing"
app_publisher = "darwishdev"
app_description = "Billing for hotel"
app_email = "a.darwish.dev@gmail.com"
app_license = "mit"
after_install = "abc_billing.setup.installer.after_install"
after_migrate = "abc_billing.setup.installer.after_migrate"
